### ISSUE TITLE
Q3 Improvements to website

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/website#168]
This initiative is a centralized location to track all improvements planned for the tattle website. 

# Features
## Improve Content discoverability 
- [x] https://github.com/tattle-made/website/issues/108
- [x] https://github.com/tattle-made/website/issues/26
- [x] https://github.com/tattle-made/website/issues/109
- [ ] #170
- [ ] #171
- [x] #172
- [ ] Allow users to subscribe to a product updates
- [ ] #173
- [ ] #176
- [x] #174
- [x] #175

## Improve User Experience for adding and editing content
- [ ] Create a GUI for the team to add and edit content
- [ ] Add documentation in wiki to show how someone can add a new blog post. 
Best practices and caveat.

## Improve DX for managing website
- [x] #183
- [x] Review and update README 
- [x] #177

**Comment by maanasb01** [comment]
Hello, Can you assign this issue to me please, I would like to work on it.

**Comment by dennyabrain** [comment]
I am happy with the progress we have made on this initiative. @maanasb01 is fully ramped up on the website code now. I'm closing this initiative. We'll create a new consolidated initiative for other improvements.
